# Trade list (supervised MM session).
[[markets]]
slug    = "clarity-act-signed-into-law-in-2026"
profile = "one_way"
enabled = true

[[markets]]
slug    = "xi-jinping-out-before-2027"
profile = "one_way"
enabled = true


[[markets]]
slug    = "will-china-invade-taiwan-before-2027"
profile = "one_way"
enabled = true

[[markets]]
slug    = "will-china-invade-taiwan-by-december-31-2027"
profile = "one_way"
enabled = true

[[markets]]
slug    = "will-china-invade-taiwan-by-june-30-2027"
profile = "one_way"
enabled = true

[[markets]]
slug    = "putin-out-before-2027-346"
profile = "one_way"
enabled = true

[[markets]]
slug    = "putin-out-as-president-of-russia-by-june-30-2027"
profile = "one_way"
enabled = true

[[markets]]
slug    = "will-the-iranian-regime-fall-by-the-end-of-2026"
profile = "one_way"
enabled = true

[[markets]]
slug    = "will-the-us-confirm-that-aliens-exist-before-2027-789-924-249"
profile = "one_way"
enabled = true
